sudo: required
services:
	- docker

before_install:
	-docker build -t someshkrao/docker-react-f Dockerfile.dev .

script:
  - docker run -e CI=true someshkrao/docker-react npm run test -- --coverage
language: generic 
